# Generated by Django 4.2 on 2025-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crop_sold_alter_crop_owner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_crops',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='main.crop'),
        ),
    ]
