FROM ubuntu:24.04


ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    git \
    python3 \
    python3-pip \
    unzip \
    docker.io \
    && rm -rf /var/lib/apt/lists/*



# AWS CLI v2

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip



# kubectl

RUN curl -LO \
    "https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl" \
    && install kubectl /usr/local/bin/kubectl



RUN aws --version && \
    kubectl version --client && \
    docker --version



CMD ["sleep","999999"]